apiVersion: v1
kind: Secret
metadata:
  name: gitlab-runner
  namespace: gitlab
type: Opaque
stringData:
  runner-registration-token: "" # поле оставлять пустым, способ устарел
  runner-token: "glrt-haAD9no41YLEnJfNEdJu" #2
#  runner-token: "glrt-WGXp7y8sR9q6p-E73dEx" #4