apiVersion: v1
kind: Service
metadata:
  name: monitoring-grafana
  namespace: monitoring
spec:
  type: NodePort
  selector:
    app.kubernetes.io/instance: monitoring
    app.kubernetes.io/name: grafana
  ports:
    - name: http-web
      protocol: TCP
      port: 80  
      targetPort: 3000 
      nodePort: 30010 
