---
- name: Install ClickHouse
  hosts:  hw82-vector
  handlers:
    - name: Start clickhouse service
      become: true
      ansible.builtin.service:
        name: clickhouse-server
        state: restarted

  tasks:
    - name: AptInst
      become: true
      apt:
        name:
        - apt-transport-https
        - ca-certificates
        - dirmngr
        state: present

    - name: Add ClickHouse repository key
      become: true
      apt_key:
        keyserver: hkp://keyserver.ubuntu.com:80
        id: 8919F6BD2B48D754

    - name: Add ClickHouse repository
      become: true
      copy:
        content: "deb https://packages.clickhouse.com/deb stable main\n"
        dest: /etc/apt/sources.list.d/clickhouse.list

    - name: Update APT cache
      become: true
      apt:
        update_cache: yes

    - name: Install ClickHouse server and client
      become: true
      apt:
        name:
          - clickhouse-server
          - clickhouse-client
        state: present

    - name: Start ClickHouse server
      become: true
      service:
        name: clickhouse-server
        state: started

    - name: Flush handlers
      meta: flush_handlers
    - name: Create database
      ansible.builtin.command: "clickhouse-client -q 'create database logs;'"
      register: create_db
      failed_when: create_db.rc != 0 and create_db.rc !=82
      changed_when: create_db.rc == 0
