---
  - src: git@github.com:AlexeySetevoi/ansible-clickhouse.git
    scm: git
    version: "1.11.0"
    name: clickhouse

  - src: git@github.com:VodyakovDenis/vector-role.git
    scm: git
    name: vector-role

  - src: git@github.com:VodyakovDenis/lighthouse-role.git
    scm: git
    name: lighthouse-role
