---
- name: clickhouse
  hosts: clickhouse
  roles:
    - clickhouse

- name: vector
  hosts: vector
  roles:
    -  vector-role
  tags:
    - vector
- name: lighthouse
  hosts: lighthouse
  roles:
    -  lighthouse-role
  tags:
    - lighthouse
